#!/usr/bin/env bash
ELM_MAKE=node_modules/.bin/elm-make
UA_PATH=elm/user-agent
DIST_PATH=dist

[ -d dist ] || mkdir dist
$ELM_MAKE $UA_PATH/Main.elm --output $DIST_PATH/index.html
$ELM_MAKE $UA_PATH/Pages.elm --output $DIST_PATH/page.html
