#!/usr/bin/env bash
ELM_MAKE=node_modules/.bin/elm-make
UA_PATH=elm/user-agent
DIST_PATH=dist

[ -d $DIST_PATH ] || mkdir $DIST_PATH
$ELM_MAKE $UA_PATH/Main.elm --yes --output $DIST_PATH/index.html
$ELM_MAKE $UA_PATH/Pages.elm --yes --output $DIST_PATH/page.html
echo "PATH node_modules/.bin"
ls -l node_modules/.bin
echo "PATH ."
ls -l
echo "PATH ${DIST_PATH}"
ls -l $DIST_PATH
